name: cmake_build
description: Build using conan and cmake
inputs:
  build_type:
    required: true
    description: The build type (Release|Debug)
  args:
    required: false
    description: The additional argument
    default: "-s compiler.cppstd=gnu20 -o '&:coverage=ON' -o '&:cppcheck=ON' -o '&:valgrind=ON'"
runs:
  using: composite
  steps:
    # Build
    - name: Build
      shell: bash
      run: >
        conan build .
        -s build_type=${{inputs.build_type}}
        --build=missing
        ${{inputs.args}}
