name: cmake_build
description: Build using conan and cmake
inputs:
  build_type:
    required: true
    description: The build type (Release|Debug)
runs:
  using: composite
  steps:
    # Build
    - if: ${{ inputs.build_type == 'Release' }}
      name: Build
      shell: bash
      run: >
        conan build .
        -s compiler.cppstd=gnu20
        -s build_type=${{inputs.build_type}}
        --build=missing

    - if: ${{ inputs.build_type == 'Debug' }}
      name: Build
      shell: bash
      run: >
        conan build .
        -s compiler.cppstd=gnu20
        -s build_type=${{inputs.build_type}}
        --build=missing
        -o '&:coverage=ON'
        -o '&:cppcheck=ON'
        -o '&:valgrind=ON'