name: cmake_build
description: Build using conan and cmake
inputs:
  build_type:
    required: true
    description: The build type (Release|Debug)
  args:
    required: false
    description: The additional argument
    default: ""
runs:
  using: composite
  steps:
    # Build
    - name: Build
      shell: bash
      run: >
        conan build .
        -pr:a ${{runner.os}}-latest
        -s build_type=${{inputs.build_type}}
        --build=missing
        ${{inputs.args}}
