name: Get C++ Tools
description: Install the required tools for c++ compilation and analysis
inputs:
  KEY:
    required: true
    description: key for cache
runs:
  using: composite
  steps:
    # Download tools for linux
    - if: runner.os == 'Linux'
      name: Install
      shell: bash
      run : sudo apt-get install -y gcc gcovr lcov libncurses5-dev cppcheck valgrind doxygen graphviz
    # Install conan
    - name: Get Conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.11.0
    # Cache conan local repository
    - name: Cache conan local repository
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        # conan files are stored in `~/.conan2` on Linux
        path: ~/.conan2
        key: ${{ inputs.KEY }}
    # If no cache found, generate profile
    - if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
      name: Create default profile
      shell: bash
      run: >
        conan config install https://github.com/KobNael/nael_cpp_action.git --args="-b main"
    # Install python requirements
    - if: runner.os == 'Linux' && ${{ hashFiles('requirements.txt') != '' }}
      name: Get Python requirements
      shell: bash
      run : pip3 install -r requirements.txt
