name: Get C++ Tools
description: Install the required tools for c++ compilation and analysis
runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run : sudo apt-get install -y gcc gcovr lcov libncurses5-dev cppcheck valgrind
