name: tests_cpp
description: Launch code quality analysis
inputs:
  build_type:
    required: true
    description: The build type (Release|Debug)
  working_dir:
    required: false
    description: The working directory
    default: ${{github.workspace}}/builds/Linux/gcc/13/x86_64/${{inputs.build_type}}
runs:
  using: composite
  steps:
    # UnitTests
    - name: Run UnitTests
      working-directory: ${{inputs.working_dir}}
      shell: bash
      run: make run_unit_tests
    # Coverage
    - if: ${{ inputs.build_type == 'Debug' }}
      name: Run Coverage
      working-directory: ${{inputs.working_dir}}
      shell: bash
      run: make run_coverage
    # Memcheck
    - if: ${{ inputs.build_type == 'Debug' }}
      name: Run Valgrind
      working-directory: ${{inputs.working_dir}}
      shell: bash
      run: make run_memcheck

