name: tests_cpp
description: Launch code quality analysis
inputs:
  BUILD_TYPE:
    required: true
    description: The build type (Release|Debug)
  ROOT_DIR:
    required: false
    description: The working directory
    default: ${{github.workspace}}/builds/Linux/gcc/13/x86_64/
  WITH_COVERAGE:
    required: false
    description: Should the coverage target run
    default: true
runs:
  using: composite
  steps:
    # UnitTests
    - name: Run UnitTests
      working-directory: ${{inputs.ROOT_DIR}}${{inputs.BUILD_TYPE}}
      shell: bash
      run: cmake --build . --target run_unit_tests --config ${{inputs.BUILD_TYPE}}
    # Coverage
    - if: ${{ inputs.BUILD_TYPE == 'Debug' && inputs.WITH_COVERAGE }}
      name: Run Coverage
      working-directory: ${{inputs.ROOT_DIR}}${{inputs.BUILD_TYPE}}
      shell: bash
      run: cmake --build . --target run_coverage
    # Memcheck
    - if: ${{ inputs.BUILD_TYPE == 'Debug' }}
      name: Run Valgrind
      working-directory: ${{inputs.ROOT_DIR}}${{inputs.BUILD_TYPE}}
      shell: bash
      run: cmake --build . --target run_memcheck

