name: install_cpp
description: Launch install and upload binary dir
inputs:
  BUILD_DIR:
    required: false
    description: The working directory to launch install command
    default: ${{github.workspace}}/builds/Linux/gcc/13/x86_64/Release/
runs:
  using: composite
  steps:
    # Install
    - name: Run install
      working-directory: ${{inputs.BUILD_DIR}}
      shell: bash
      run: cmake --install .
    # Upload
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: ${{runner.os}}-binaries
        path: |
          ${{github.workspace}}/lib/
          ${{github.workspace}}/include/
          ${{github.workspace}}/bin/
          ${{github.workspace}}/share/
