############################
# Workflow for C++ project
############################
name: Reusable C++ Workflow
#================
# Inputs
#================
on:
  workflow_call:
    inputs:
      RUN_SONAR:
        required: false
        type: boolean
        default: true
      CHECK_QUALITY_GATE:
        required: false
        type: boolean
        default: true
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      GH_PAT:
        required: true
#=================
# Pipelines
#=================
jobs:
  #------------------
  # Ubuntu build
  #------------------
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    # Steps
    steps:
    # Checkout sources
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive # Submodules needed
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # Get c++ tools
    - name: Get C++ Tools
      uses: KobNael/nael_cpp_action/setup_cpp@v1
      with:
        key: ${{ hashFiles('./conanfile.py') }}-${{ hashFiles('./CMakeLists.txt') }}
    # Release Build
    - name: Release conan build
      uses: KobNael/nael_cpp_action/cmake_build@v1
      with:
        build_type: Release
    # Test
    - name: Release analysis
      uses: KobNael/nael_cpp_action/tests_cpp@v1
      with:
        build_type: Release
    # Debug Build
    - name: Debug conan build
      uses: KobNael/nael_cpp_action/cmake_build@v1
      with:
        build_type: Debug
    # Test
    - name: Debug analysis
      uses: KobNael/nael_cpp_action/tests_cpp@v1
      with:
        build_type: Debug
    # Sonar analysis
    - if: ${{ inputs.RUN_SONAR }}
      name: Sonar analysis
      uses: SonarSource/sonarqube-scan-action@v4
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
    # Sonar Quality Gate
    - if: ${{ inputs.RUN_SONAR && inputs.CHECK_QUALITY_GATE }}
      name: SonarQube quality gate check
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret

  #------------------
  # Windows build
  #------------------
  windows-latest-build:
    runs-on: windows-latest
    # Steps
    steps:
        # Checkout sources
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive # Submodules needed
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Get Conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.11.0
      - name: Setup Profile
        run: >
          conan config install https://github.com/KobNael/nael_cpp_action.git --args="-b win_compil"
    # Build
      - name: Build
        run: >
          conan build .
          -pr:a windows-latest
