############################
# Workflow for C++ project
############################
name: Reusable C++ Workflow
#================
# Inputs
#================
on:
  workflow_call:
    inputs:
      RUN_SONAR:
        required: false
        type: boolean
        default: true
      CHECK_QUALITY_GATE:
        required: false
        type: boolean
        default: true
      UPLOAD_ARTIFACT:
          required: false
          type: boolean
          default: false
      ARTIFACT_NAME:
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      GH_PAT:
        required: true
#=================
# Pipelines
#=================
jobs:
  #------------------
  # Ubuntu build
  #------------------
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    # Steps
    steps:
    # Checkout sources
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: recursive # Submodules needed
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # Get c++ tools
    - name: Get C++ Tools
      uses: KobNael/nael_cpp_action/setup_cpp@win_compil
      with:
        key: nux-${{ hashFiles('./conanfile.py') }}-${{ hashFiles('./CMakeLists.txt') }}
    # Release Build
    - name: Release conan build
      uses: KobNael/nael_cpp_action/cmake_build@win_compil
      with:
        BUILD_TYPE: Release
    # Test
    - name: Release analysis
      uses: KobNael/nael_cpp_action/tests_cpp@win_compil
      with:
        BUILD_TYPE: Release
    # Debug Build
    - name: Debug conan build
      uses: KobNael/nael_cpp_action/cmake_build@win_compil
      with:
        BUILD_TYPE: Debug
        ARGS: " -o '&:coverage=ON' -o '&:cppcheck=ON' -o '&:valgrind=ON'"
    # Test
    - name: Debug analysis
      uses: KobNael/nael_cpp_action/tests_cpp@win_compil
      with:
        BUILD_TYPE: Debug
    # Sonar analysis
    - if: ${{ inputs.RUN_SONAR }}
      name: Sonar analysis
      uses: SonarSource/sonarqube-scan-action@v4
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
    # Sonar Quality Gate
    - if: ${{ inputs.RUN_SONAR && inputs.CHECK_QUALITY_GATE }}
      name: SonarQube quality gate check
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # SonarQube URL is stored in a GitHub secret
    # Install & upload
    - name: Install & upload
      uses: KobNael/nael_cpp_action/install@win_compil
      with:
        ARTIFACT_NAME: ${{inputs.ARTIFACT_NAME}}

  #------------------
  # Windows build
  #------------------
  windows-latest-build:
    runs-on: windows-latest
    # Steps
    steps:
        # Checkout sources
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive # Submodules needed
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # Get c++ tools
      - name: Get C++ Tools
        uses: KobNael/nael_cpp_action/setup_cpp@win_compil
        with:
          key: win-${{ hashFiles('./conanfile.py') }}-${{ hashFiles('./CMakeLists.txt') }}
      # Release Build
      - name: Release conan build
        uses: KobNael/nael_cpp_action/cmake_build@win_compil
        with:
          BUILD_TYPE: Release
      # Test
      - name: Release analysis
        uses: KobNael/nael_cpp_action/tests_cpp@win_compil
        with:
          BUILD_TYPE: Release
          ROOT_DIR: ${{github.workspace}}\builds\Windows\gcc\12\x86_64\
      # Install & upload
      - name: Install & upload
        uses: KobNael/nael_cpp_action/install@win_compil
        with:
          BUILD_DIR: ${{github.workspace}}\builds\Windows\gcc\12\x86_64\Release\
          ARTIFACT_NAME: ${{inputs.ARTIFACT_NAME}}
